/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_quiestce;

import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author clecann
 */
public class FenetreAjoutPerso extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    public FenetreAjoutPerso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jComboBoxSexe = new javax.swing.JComboBox();
        jLabelChapeau = new javax.swing.JLabel();
        jLabelCheveux = new javax.swing.JLabel();
        jLabelYeux = new javax.swing.JLabel();
        jLabelLunettes = new javax.swing.JLabel();
        jLabelBarbe = new javax.swing.JLabel();
        jLabelMoustache = new javax.swing.JLabel();
        jLabelNez = new javax.swing.JLabel();
        jLabelBouche = new javax.swing.JLabel();
        jLabeBoucle = new javax.swing.JLabel();
        jComboBoxChapeau = new javax.swing.JComboBox();
        jComboBoxCheveux = new javax.swing.JComboBox();
        jComboBoxLunettes = new javax.swing.JComboBox();
        jComboBoxBarbe = new javax.swing.JComboBox();
        jComboBoxMoustache = new javax.swing.JComboBox();
        jComboBoxNez = new javax.swing.JComboBox();
        jComboBoxBouche = new javax.swing.JComboBox();
        jComboBoxBoucle = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxYeux = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(100, 200));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel2.setText("Création personnage");

        jLabelSexe.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelSexe.setText("Sexe");

        jComboBoxSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "un homme", "une femme" }));
        jComboBoxSexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexeActionPerformed(evt);
            }
        });

        jLabelChapeau.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelChapeau.setText("Chapeau");

        jLabelCheveux.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelCheveux.setText("Cheveux");

        jLabelYeux.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelYeux.setText("Yeux");

        jLabelLunettes.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelLunettes.setText("Lunettes");

        jLabelBarbe.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelBarbe.setText("Barbe");

        jLabelMoustache.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelMoustache.setText("Moustache");

        jLabelNez.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelNez.setText("Nez");

        jLabelBouche.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabelBouche.setText("Bouche");

        jLabeBoucle.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabeBoucle.setText("Boucle d'oreille");

        jComboBoxChapeau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "n'a pas de chapeau", "a un chapeau" }));
        jComboBoxChapeau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChapeauActionPerformed(evt);
            }
        });

        jComboBoxCheveux.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a les cheveux blancs", "a les cheveux noirs", "a les cheveaux blonds", "a les cheveux bruns", "a les cheveux roux", "est chauve" }));

        jComboBoxLunettes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a des lunettes", "n'a pas de lunettes" }));

        jComboBoxBarbe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a une barbe", "n'a pas de barbe" }));

        jComboBoxMoustache.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a une moustache", "n'a pas de moustache" }));

        jComboBoxNez.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a un petit nez", "a un gros nez" }));

        jComboBoxBouche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a une petite bouche", "a une grande bouche" }));

        jComboBoxBoucle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a des boucles d'oreilles", "n'a pas de boucle d'oreille" }));
        jComboBoxBoucle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBoucleActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel13.setText("Prenom");

        jTextFieldPrenom.setText("Prenom");
        jTextFieldPrenom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jButton1.setText("Continuer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxYeux.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a les yeux marrons", "a les yeux bleus", "a les yeux verts", "a les yeux gris" }));
        jComboBoxYeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYeuxActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_quiestce/akinator_defi2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelSexe)
                        .addGap(44, 44, 44)
                        .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabelBarbe)
                        .addGap(47, 47, 47)
                        .addComponent(jComboBoxBarbe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelChapeau)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxChapeau, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabelMoustache)
                        .addGap(30, 30, 30)
                        .addComponent(jComboBoxMoustache, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelCheveux)
                                .addGap(22, 22, 22)
                                .addComponent(jComboBoxCheveux, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelYeux)
                                .addGap(45, 45, 45)
                                .addComponent(jComboBoxYeux, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabelNez)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBouche)
                                .addGap(40, 40, 40)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxBouche, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxNez, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelLunettes)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxLunettes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabeBoucle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBoucle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxBarbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBarbe))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelChapeau))
                    .addComponent(jComboBoxChapeau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxMoustache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMoustache, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelCheveux))
                    .addComponent(jComboBoxCheveux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxNez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNez)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxYeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxBouche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBouche))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelYeux)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxLunettes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxBoucle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeBoucle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelLunettes)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexeActionPerformed

    private void jComboBoxChapeauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChapeauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChapeauActionPerformed

    private void jComboBoxBoucleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBoucleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBoucleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // annuler :
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxYeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYeuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxYeuxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Personnage nouveauPerso = new Personnage(jTextFieldPrenom.getText());
        
        nouveauPerso.addCaract(new Caracteristiques("Sexe", jComboBoxSexe.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Chapeau", jComboBoxChapeau.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Cheveux", jComboBoxCheveux.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Yeux", jComboBoxYeux.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Lunettes", jComboBoxLunettes.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Barbe", jComboBoxBarbe.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Moustache", jComboBoxMoustache.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Nez", jComboBoxNez.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Bouche", jComboBoxBouche.getSelectedItem().toString()));
        nouveauPerso.addCaract(new Caracteristiques("Boucles d'oreille", jComboBoxBoucle.getSelectedItem().toString()));
        
        /* On importe la base de donnée de jeu, on lui ajoute le nouveau personnage */
        boolean trouve= false; int i=0;
        BaseDD maBase = new BaseDD();
        maBase.lireFichier("quiestce");
        while(!trouve && i< maBase.getBase().size()){
            if(maBase.getBase().get(i).equals(nouveauPerso)){
                trouve=true;
            }
            i++;
        }
        if(!trouve && nouveauPerso.getPrenom() != "Prenom"){
             maBase.addPerso(nouveauPerso);
            /* On réécrit le fichier cvs qui contient la liste de perso */
            maBase.ecrireFichier("quiestce.csv");
        }
        this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAjoutPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAjoutPerso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxBarbe;
    private javax.swing.JComboBox jComboBoxBouche;
    private javax.swing.JComboBox jComboBoxBoucle;
    private javax.swing.JComboBox jComboBoxChapeau;
    private javax.swing.JComboBox jComboBoxCheveux;
    private javax.swing.JComboBox jComboBoxLunettes;
    private javax.swing.JComboBox jComboBoxMoustache;
    private javax.swing.JComboBox jComboBoxNez;
    private javax.swing.JComboBox jComboBoxSexe;
    private javax.swing.JComboBox jComboBoxYeux;
    private javax.swing.JLabel jLabeBoucle;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBarbe;
    private javax.swing.JLabel jLabelBouche;
    private javax.swing.JLabel jLabelChapeau;
    private javax.swing.JLabel jLabelCheveux;
    private javax.swing.JLabel jLabelLunettes;
    private javax.swing.JLabel jLabelMoustache;
    private javax.swing.JLabel jLabelNez;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelYeux;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables

    private boolean creation = false;
    
    public void generer(){
        this.setVisible(true);

        
    }
    

}
